# Generated by Django 5.0.6 on 2024-05-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arabapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('productname', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('productimage', models.ImageField(blank=True, null=True, upload_to='productimages')),
            ],
        ),
    ]
